
import java.awt.Dimension;

/**
 *
 * @author Jure Grgic
 */
public class FioccoDiNeveFrame extends javax.swing.JFrame {

    /**
     * Creates new form FioccoDiNeveFrame
     */
    public FioccoDiNeveFrame() {
        initComponents();
        this.setMinimumSize(new Dimension(1024, 768));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fioccoDiNeve = new FioccoDiNeve();
        jPanel = new javax.swing.JPanel();
        resetAllPoints = new javax.swing.JButton();
        generateSnowFlake = new javax.swing.JButton();
        saveSnowFlakeImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout fioccoDiNeveLayout = new javax.swing.GroupLayout(fioccoDiNeve);
        fioccoDiNeve.setLayout(fioccoDiNeveLayout);
        fioccoDiNeveLayout.setHorizontalGroup(
            fioccoDiNeveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        fioccoDiNeveLayout.setVerticalGroup(
            fioccoDiNeveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        getContentPane().add(fioccoDiNeve, java.awt.BorderLayout.CENTER);

        jPanel.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel.setPreferredSize(new java.awt.Dimension(518, 50));
        jPanel.setLayout(new java.awt.GridLayout());

        resetAllPoints.setText("Reset");
        resetAllPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAllPointsActionPerformed(evt);
            }
        });
        jPanel.add(resetAllPoints);

        generateSnowFlake.setText("Generate");
        generateSnowFlake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSnowFlakeActionPerformed(evt);
            }
        });
        jPanel.add(generateSnowFlake);

        saveSnowFlakeImage.setText("Save");
        saveSnowFlakeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSnowFlakeImageActionPerformed(evt);
            }
        });
        jPanel.add(saveSnowFlakeImage);

        getContentPane().add(jPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetAllPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAllPointsActionPerformed
        fioccoDiNeve.resetLists();
    }//GEN-LAST:event_resetAllPointsActionPerformed

    private void generateSnowFlakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSnowFlakeActionPerformed
        this.setSize(1024, 768);
        this.setResizable(false);
        fioccoDiNeve.generateSnowFlake();
    }//GEN-LAST:event_generateSnowFlakeActionPerformed

    private void saveSnowFlakeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSnowFlakeImageActionPerformed
        if(fioccoDiNeve.isGenerated()){
            fioccoDiNeve.saveImage();
        }
    }//GEN-LAST:event_saveSnowFlakeImageActionPerformed

    /**
     * @param args gli argomenti passati a linea di comando.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FioccoDiNeveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FioccoDiNeveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FioccoDiNeveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FioccoDiNeveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FioccoDiNeveFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FioccoDiNeve fioccoDiNeve;
    private javax.swing.JButton generateSnowFlake;
    private javax.swing.JPanel jPanel;
    private javax.swing.JButton resetAllPoints;
    private javax.swing.JButton saveSnowFlakeImage;
    // End of variables declaration//GEN-END:variables
}
